# Generated by Django 3.0.3 on 2020-02-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200210_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fio',
            new_name='full_name',
        ),
    ]
