# Generated by Django 3.0.3 on 2020-02-11 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200210_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
