# Generated by Django 3.0.3 on 2020-02-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20200211_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contribution',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Вклад'),
        ),
    ]
