# Generated by Django 3.0.3 on 2020-02-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_user_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='self_contribution',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Свой Вклад'),
        ),
    ]
