# Generated by Django 3.0.3 on 2020-02-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_user_self_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена за кв.м'),
        ),
    ]
