# Generated by Django 3.0.3 on 2020-02-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20200214_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Цена за кв.м'),
        ),
    ]
