# Generated by Django 3.0.3 on 2020-02-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20200214_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Цена за кв.м'),
        ),
    ]
