# Generated by Django 3.0.3 on 2020-02-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20200214_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Должность'),
        ),
    ]
