# Generated by Django 3.0.3 on 2020-02-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200220_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerates',
            name='course',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
